spring:
  # --- Local DB Connection ---
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 로컬은 SSL 불필요, 개발 편의성 옵션 추가
    url: jdbc:mysql://${DB_URL}?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # --- Local JPA  ---
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  # --- Local Thymeleaf (즉시 반영) ---
  thymeleaf:
    cache: false # 새로고침 시 변경사항 즉시 반영
    check-template-location: true

# --- [Custom] 파일 저장소 전략 (로컬) ---
app:
  file:
    storage:
      type: local # 로컬 디스크에 저장
      local-path: ${LOCAL_FILE_PATH:C:/shop/images/}
      s3-bucket: ${S3_BUCKET_NAME:dummy-bucket} # 로컬에선 안쓰지만 플레이스홀더



# ==========================================
# [개발 전용] 로깅 & 디버깅 (P6Spy)
# ==========================================
decorator:
  datasource:
    enabled: true
    p6spy:
      enable-logging: true
      logging: slf4j
      log-file: disable

logging:
  level:
    root: INFO
    com.mall.project: DEBUG # 내 코드는 자세히 보기
    p6spy: INFO            # 쿼리 로그 보기
    org.hibernate.SQL: INFO


toss:
  client-key: ${TOSS_CLIENT_KEY}
  secret-key: ${TOSS_SECRET_KEY}
