spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view:  false

  profiles:
    active: local

  data:
    redis:
      port: 6379
      host: localhost

  servlet:
    multipart:
      max-file-size: 5MB # 단일 파일 최대
      max-request-size: 50MB # 여러 파일 합계
file:
  upload:
    base-path: ${UPLOAD_BASE_PATH:./uploads}
    rooms-path: rooms